#!/usr/bin/env bash

perl -mJSON -e '@ws=@{JSON::decode_json(`i3-msg -t get_workspaces`)}; print join("\n", map { $_->{name} } @ws);' | $HOME/scripts/dmenu_run -p "Workspace: " | xargs printf 'workspace %s' | xargs i3-msg
