#!/usr/bin/env bash

perl -mJSON -e '@marks=@{JSON::decode_json(`i3-msg -t get_marks`)}; print join("\n", @marks);' | $HOME/dmenu-4.5/dmenu_run -p "Go: " | xargs printf '[con_mark="%s"] focus' | xargs i3-msg
