#!/usr/bin/env bash

perl -mJSON -e '@ws=@{JSON::decode_json(`i3-msg -t get_workspaces`)}; print join("\n", map { $_->{name} } @ws);' | $HOME/dmenu-4.5/dmenu_run -p "Move\ to\ workspace: " | xargs printf 'move container to workspace %s' | xargs i3-msg
