#!/usr/bin/env sh

i3status | (read line && echo $line && read line && echo $line && while :
do
    read line
    wintitle=$(xtitle -f "[{\"name\":\"title\",\"align\":\"center\",\"min_width\":1200,\"full_text\":\"%s\"},")
    echo "${line/[/$wintitle}" || exit 1
done)
